name: Deploy to Production

on:
  push:
    branches: [ prod ]

env:
  BASE_URL: "/management"
  BACKEND_HOST: "https://order-system.octoberserver.net"
  MAIN_APP_URL: "https://zl-order-system.github.io/app/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: |
          export BASE_URL=${{ env.BASE_URL }}
          export BACKEND_HOST=${{ env.BACKEND_HOST }}
          export MAIN_APP_URL=${{ env.MAIN_APP_URL }}
          npm run build
      - name: Deploy
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'dist'
          destination-github-username: 'zl-order-system'
          destination-repository-name: 'zl-order-system.github.io'
          user-email: example@example.com
          target-branch: main
          target-directory: management
          create-target-branch-if-needed: true
